# Source: https://github.com/actions/starter-workflows/blob/main/pages/jekyll-gh-pages.yml

name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - 1x-developer

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Install NodeJs dependencies
        run: npm install
      - name: Build Jekyll site using NodeJs (for postcss)
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
